
const sampleData = [
    {
      shape_name: "Round",
      shape_size: "Medium",
      cut_name: "Brilliant",
      clarity_name: "VS1",
      origin_name: "Natural",
      treatment_name: null,
      master_cut_name: "Excellent",
      metal_type: "Gold",
      metal_purity: "18K",
      metal_color_name: "Yellow",
      gold_color: null,
      diamond_color_name: "Colorless",
      diamond_clarity: "SI1",
      number_of_accent_stones: null,
      total_piece_dimensions_l: 20,
      total_piece_dimensions_w: 20,
      total_piece_dimensions_d: 5,
      center_stone_dimensions_l: 10,
      center_stone_dimensions_w: 10,
      center_stone_dimensions_d: 5,
      ring_size: "7",
      band_thickness: 2,
      band_width: 3,
      backings_style: null,
      type_of_backings: null,
      type_of_bail: null,
      dimensions_of_bail_l: null,
      dimensions_of_bail_w: null,
      dimensions_of_bail_d: null,
      fancy_jewelry_big_number: null,
      fancy_jewelry_stone_price: null,
      fancy_jewelry_stone: null,
      gemstone_cats_eye: null,
      gemstone_star_stone: null,
      color_change_stone: null,
      fancy_cut: null,
      deal_of_the_month: null,
      jewel_box: null
    },
    {
      shape_name: "Princess",
      shape_size: "Small",
      cut_name: "Ideal",
      clarity_name: "VVS2",
      origin_name: "Lab-Created",
      treatment_name: "Heat Treated",
      master_cut_name: "Signature",
      metal_type: "Silver",
      metal_purity: "925",
      metal_color_name: "White",
      gold_color: null,
      diamond_color_name: "Blue",
      diamond_clarity: "VS1",
      number_of_accent_stones: null,
      total_piece_dimensions_l: 15,
      total_piece_dimensions_w: 15,
      total_piece_dimensions_d: 4,
      center_stone_dimensions_l: 8,
      center_stone_dimensions_w: 8,
      center_stone_dimensions_d: 4,
      ring_size: "6",
      band_thickness: 1,
      band_width: 2,
      backings_style: "Push Back",
      type_of_backings: "Butterfly",
      type_of_bail: "Hidden",
      dimensions_of_bail_l: null,
      dimensions_of_bail_w: null,
      dimensions_of_bail_d: null,
      fancy_jewelry_big_number: "FJB123",
      fancy_jewelry_stone_price: 100,
      fancy_jewelry_stone: "Diamond",
      gemstone_cats_eye: null,
      gemstone_star_stone: null,
      color_change_stone: null,
      fancy_cut: null,
      deal_of_the_month: null,
      jewel_box: null
    },
    {
      shape_name: "Oval",
      shape_size: "Large",
      cut_name: "Premium",
      clarity_name: "SI1",
      origin_name: "Natural",
      treatment_name: null,
      master_cut_name: "Masterpiece",
      metal_type: "Gold",
      metal_purity: "14K",
      metal_color_name: "Rose",
      gold_color: null,
      diamond_color_name: "Colorless",
      diamond_clarity: "VS2",
      number_of_accent_stones: null,
      total_piece_dimensions_l: 25,
      total_piece_dimensions_w: 20,
      total_piece_dimensions_d: 6,
      center_stone_dimensions_l: 12,
      center_stone_dimensions_w: 10,
      center_stone_dimensions_d: 6,
      ring_size: "8",
      band_thickness: 2,
      band_width: 3,
      backings_style: "Screw Back",
      type_of_backings: "Hinged",
      type_of_bail: "Fixed",
      dimensions_of_bail_l: null,
      dimensions_of_bail_w: null,
      dimensions_of_bail_d: null,
      fancy_jewelry_big_number: null,
      fancy_jewelry_stone_price: null,
      fancy_jewelry_stone: null,
      gemstone_cats_eye: "Yes",
      gemstone_star_stone: "No",
      color_change_stone: "Yes",
      fancy_cut: null,
      deal_of_the_month: null,
      jewel_box: null
    },
    {
      shape_name: "Cushion",
      shape_size: "Medium",
      cut_name: "Good",
      clarity_name: "SI2",
      origin_name: "Treated",
      treatment_name: "Coating",
      master_cut_name: "Custom",
      metal_type: "Platinum",
      metal_purity: "950",
      metal_color_name: "White",
      gold_color: null,
      diamond_color_name: "Yellow",
      diamond_clarity: "I1",
      number_of_accent_stones: null,
      total_piece_dimensions_l: 22,
      total_piece_dimensions_w: 18,
      total_piece_dimensions_d: 5,
      center_stone_dimensions_l: 11,
      center_stone_dimensions_w: 9,
      center_stone_dimensions_d: 5,
      ring_size: "7.5",
      band_thickness: 2,
      band_width: 3,
      backings_style: null,
      type_of_backings: null,
      type_of_bail: null,
      dimensions_of_bail_l: null,
      dimensions_of_bail_w: null,
      dimensions_of_bail_d: null,
      fancy_jewelry_big_number: null,
      fancy_jewelry_stone_price: null,
      fancy_jewelry_stone: null,
      gemstone_cats_eye: null,
      gemstone_star_stone: null,
      color_change_stone: null,
      fancy_cut: null,
      deal_of_the_month: null,
      jewel_box: null
    }
  ];
  
  module.exports = sampleData;
  