
#Get all promotion 

GET http://localhost:3000/promotion/

# GEt one promotion with id 

###

GET  http://localhost:3000/promotion/65ebe67b0ffa1e4d6a24afa7/

####

##Create a promotion 

POST http://localhost:3000/promotion
Content-Type: application/json

{
    "PromotionID": 5,
    "PromotionName": "Spring Sale TEST",
    "PromotionType": "Discount",
    "StartDate": "2024-03-01T00:00:00Z",
    "EndDate": "2024-03-15T23:59:59Z",
    "Description": "Get 20% off on all spring collection items.",
    "IsActive": true,
    "CreatedAt": "2024-02-15T12:00:00Z",
    "UpdatedAt": "2024-02-20T08:30:00Z"
}


##Update the promotion 

####
PATCH http://localhost:3000/promotion/65f1ffac8fc34c99baef4783
Content-Type: application/json

{
    "PromotionID": 5,
    "PromotionName": "Spring Sale TEST Gowtham",
    "PromotionType": "Discount",
    "StartDate": "2024-03-01T00:00:00Z",
    "EndDate": "2024-03-15T23:59:59Z",
    "Description": "Get 20% off on all spring collection items.",
    "IsActive": true,
    "CreatedAt": "2024-02-15T12:00:00Z",
    "UpdatedAt": "2024-02-20T08:30:00Z"
}

## Delete the promotion 

##### 
DELETE http://localhost:3000/promotion/65f1ffac8fc34c99baef4783



